### ISSUE TITLE
Setting http status code in controller

### ISSUE THREAD

**Issue by mikmedina** [ollita7/kiwi#21]
Is there a way to set the status code in the controller?

**Comment by ollita7** [comment]
Hi @mikmedina thanks for your question!

Yes it is posible modifying the response

```
@Get('/sample)
public sample(request) {
        response.statusCode = 201;
        return { text: '201 http code return'};
}
```

Let me know if you  need more help!

**Comment by mikmedina** [comment]
Thank you!

**Comment by mikmedina** [comment]
I've read the source code and you can access it in the controller like this.
`
    @Get('/history2')
    async getHistory2(
      @QueryParam() params: any,
      @HeaderParam('x-api-key') apiKey: string,
      request: any,
      response: any,
    ) {
`

**Comment by ollita7** [comment]
Also you have other way now if you don't want to have a parameter response.

```
@Get('/sample')
async sample( ) {
    this.response.statusCode = 201;
}
```
