### ISSUE TITLE
Add dockerfile

### ISSUE THREAD

**Issue by mario16** [ollita7/kiwi#24]
It would be great if you can share a dockerfile suggested for docker configuration.
I think this could be very useful.
Thanks in advance!

**Comment by ollita7** [comment]
Hey @mario16 how are you?

Here you can take a look an article I wrote abour how to dockerize kiwi server

[https://wiki.cavepotlab.com/2021/01/21/dockeriza-kiwi-server/](https://wiki.cavepotlab.com/2021/01/21/dockeriza-kiwi-server/)

**Comment by mario16** [comment]
I really appreciate it! 
I will test it soon.
Thank you very much!

**Comment by mario16** [comment]
I have configured it... it works like a charm!
Thanks!
