### ISSUE TITLE
Swagger documentation not working for object arrays

### ISSUE THREAD

**Issue by matiasdelgado** [ollita7/kiwi#9]
E.g.:
`[{ id: 1, name: "Test" }, { id: 2, name: "Test 2" }]`

This only happens when the body is an array itself:
```javascript
  @Post('/')
  public async add(@Body() timesheet: TimesheetEntry[], req: IncomingMessage) {
    try {
        ...
```

**Comment by guillermochimi** [comment]
Last version has support for that.
You can take a look at the documentation

`mport { IsArray, IsInt, IsDate, IsOptional } from 'kiwi-server';

export class TimesheetEntry {
  @IsInt() projectId: number;
  @IsDate() date: Date;
  @IsOptional() @IsInt() hours?: number;
}

export class TimesheetEntries {
  @IsArray(() => TimesheetEntry)
  entries: TimesheetEntry[];
}`

**Comment by ollita7** [comment]
It is supported on new version.
Thanks for your contribution.
